# Generated by Django 3.1.7 on 2021-03-24 04:12

from django.db import migrations, models
import django.db.models.deletion
import income_states.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('revenue', models.BigIntegerField()),
                ('cost', models.BigIntegerField()),
                ('gross_profit', models.BigIntegerField()),
                ('operating_expense', models.BigIntegerField()),
                ('operating_profit', models.BigIntegerField()),
                ('net_income', models.BigIntegerField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='corps.corp')),
            ],
            options={
                'unique_together': {('code', 'date')},
            },
            managers=[
                ('objects', income_states.managers.CustomModelManager()),
            ],
        ),
    ]
