# Generated by Django 3.1.7 on 2021-05-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_states', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='financial_income',
            field=models.BigIntegerField(null=True),
        ),
    ]
