# Generated by Django 3.1.7 on 2021-05-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_states', '0002_income_financial_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.IntegerField(),
        ),
    ]
