# Generated by Django 3.1.7 on 2021-05-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_states', '0003_auto_20210512_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
