# Generated by Django 3.1.7 on 2021-03-24 04:12

from django.db import migrations, models
import django.db.models.deletion
import financial_statements.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_asset', models.BigIntegerField()),
                ('current_asset', models.BigIntegerField()),
                ('non_current_asset', models.BigIntegerField()),
                ('total_liabilities', models.BigIntegerField()),
                ('current_liabilities', models.BigIntegerField()),
                ('non_current_liabilities', models.BigIntegerField()),
                ('capital', models.BigIntegerField()),
                ('controlling_share', models.BigIntegerField()),
                ('non_controlling_share', models.BigIntegerField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='corps.corp')),
            ],
            options={
                'unique_together': {('code', 'date')},
            },
            managers=[
                ('objects', financial_statements.managers.CustomModelManager()),
            ],
        ),
    ]
