# Generated by Django 3.1.7 on 2021-05-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_statements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='date',
            field=models.IntegerField(),
        ),
    ]
