# Generated by Django 3.1.7 on 2021-04-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corp',
            name='last_update',
            field=models.DateField(null=True),
        ),
    ]
