# Generated by Django 3.1.7 on 2021-03-24 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lists.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp', models.ManyToManyField(blank=True, to='corps.Corp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('objects', lists.managers.CustomModelManager()),
            ],
        ),
    ]
