# Generated by Django 3.1.7 on 2021-03-24 04:12

import discussions.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=300)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='corps.corp')),
                ('participants', models.ManyToManyField(blank=True, related_name='discussions', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('objects', discussions.managers.CustomModelManager()),
            ],
        ),
    ]
