# Generated by Django 3.1.7 on 2021-03-24 04:12

from django.db import migrations, models
import django.db.models.deletion
import stocks.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.BigIntegerField()),
                ('high', models.BigIntegerField()),
                ('low', models.BigIntegerField()),
                ('close', models.BigIntegerField()),
                ('diff', models.BigIntegerField()),
                ('volume', models.BigIntegerField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='corps.corp')),
            ],
            options={
                'unique_together': {('code', 'date')},
            },
            managers=[
                ('objects', stocks.managers.CustomModelManager()),
            ],
        ),
    ]
