# Generated by Django 3.1.7 on 2021-04-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corps', '0002_corp_last_update'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('code_id', 'date')},
        ),
    ]
