# Generated by Django 3.1.7 on 2021-04-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210405_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='datestamp',
            field=models.BigIntegerField(null=True),
        ),
    ]
